### ISSUE TITLE
运行报错：json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by Hasen-dc** [SCIR-HI/Huatuo-Llama-Med-Chinese#15]
/home/halo_op/anaconda3/envs/py39/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/usr/local/cuda/lib64/libcudart.so.11.0'), PosixPath('/usr/local/cuda/lib64/libcudart.so')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so.11.0
CUDA SETUP: Highest compute capability among GPUs detected: 7.5
CUDA SETUP: Detected CUDA version 114
CUDA SETUP: Loading binary /home/halo_op/anaconda3/envs/py39/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda114.so...
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization.
The tokenizer class you load from this checkpoint is 'LLaMATokenizer'.
The class this function is called from is 'LlamaTokenizer'.
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 33/33 [00:14<00:00,  2.29it/s]
using lora ./lora-llama-med
Traceback (most recent call last):
  File "/mnt/datadisk0/code/Huatuo-Llama-Med-Chinese/infer.py", line 125, in <module>
    fire.Fire(main)
  File "/home/halo_op/anaconda3/envs/py39/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/halo_op/anaconda3/envs/py39/lib/python3.9/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/halo_op/anaconda3/envs/py39/lib/python3.9/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/mnt/datadisk0/code/Huatuo-Llama-Med-Chinese/infer.py", line 47, in main
    model = PeftModel.from_pretrained(
  File "/home/halo_op/anaconda3/envs/py39/lib/python3.9/site-packages/peft/peft_model.py", line 156, in from_pretrained
    PeftConfig.from_pretrained(model_id, subfolder=kwargs.get("subfolder", None)).peft_type
  File "/home/halo_op/anaconda3/envs/py39/lib/python3.9/site-packages/peft/utils/config.py", line 109, in from_pretrained
    loaded_attributes = cls.from_json_file(config_file)
  File "/home/halo_op/anaconda3/envs/py39/lib/python3.9/site-packages/peft/utils/config.py", line 129, in from_json_file
    json_object = json.load(file)
  File "/home/halo_op/anaconda3/envs/py39/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/home/halo_op/anaconda3/envs/py39/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/halo_op/anaconda3/envs/py39/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/halo_op/anaconda3/envs/py39/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
![Uploading 捕获.PNG…]()

**Comment by s65b40** [comment]
您好 请详细描述您产生此错误的前提 方便我们进行排查 谢谢
