### ISSUE TITLE
 CUDA Setup failed despite GPU being available. 

### ISSUE THREAD

**Issue by cweihua** [SCIR-HI/Huatuo-Llama-Med-Chinese#17]
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin C:\Users\86152\PycharmProjects\Huatuo-Llama-Med-Chinese-main\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
C:\Users\86152\PycharmProjects\Huatuo-Llama-Med-Chinese-main\venv\lib\site-packages\bitsandbytes\cuda_setup\main.py:145: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
  warn(msg)
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
C:\Users\86152\PycharmProjects\Huatuo-Llama-Med-Chinese-main\venv\lib\site-packages\bitsandbytes\cuda_setup\main.py:145: UserWarning: WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
  warn(msg)
C:\Users\86152\PycharmProjects\Huatuo-Llama-Med-Chinese-main\venv\lib\site-packages\bitsandbytes\cuda_setup\main.py:145: UserWarning: WARNING: No GPU detected! Check your CUDA paths. Proceeding to load CPU-only library...
  warn(msg)
CUDA SETUP: Loading binary C:\Users\86152\PycharmProjects\Huatuo-Llama-Med-Chinese-main\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA library was not detected.
CUDA SETUP: Solution 1): Your paths are probably not up-to-date. You can update them via: sudo ldconfig.
CUDA SETUP: Solution 2): If you do not have sudo rights, you can do the following:
CUDA SETUP: Solution 2a): Find the cuda library via: find / -name libcuda.so 2>/dev/null
CUDA SETUP: Solution 2b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_2a
CUDA SETUP: Solution 2c): For a permanent solution add the export from 2b into your .bashrc file, located at ~/.bashrc
Traceback (most recent call last):
  File "C:\Users\86152\PycharmProjects\Huatuo-Llama-Med-Chinese-main\infer.py", line 8, in <module>
    from peft import PeftModel
  File "C:\Users\86152\PycharmProjects\Huatuo-Llama-Med-Chinese-main\venv\lib\site-packages\peft\__init__.py", line 22, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING, PEFT_TYPE_TO_CONFIG_MAPPING, get_peft_config, get_peft_model
  File "C:\Users\86152\PycharmProjects\Huatuo-Llama-Med-Chinese-main\venv\lib\site-packages\peft\mapping.py", line 16, in <module>
    from .peft_model import (
  File "C:\Users\86152\PycharmProjects\Huatuo-Llama-Med-Chinese-main\venv\lib\site-packages\peft\peft_model.py", line 31, in <module>
    from .tuners import AdaLoraModel, LoraModel, PrefixEncoder, PromptEmbedding, PromptEncoder
  File "C:\Users\86152\PycharmProjects\Huatuo-Llama-Med-Chinese-main\venv\lib\site-packages\peft\tuners\__init__.py", line 20, in <module>
    from .lora import LoraConfig, LoraModel
  File "C:\Users\86152\PycharmProjects\Huatuo-Llama-Med-Chinese-main\venv\lib\site-packages\peft\tuners\lora.py", line 40, in <module>
    import bitsandbytes as bnb
  File "C:\Users\86152\PycharmProjects\Huatuo-Llama-Med-Chinese-main\venv\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "C:\Users\86152\PycharmProjects\Huatuo-Llama-Med-Chinese-main\venv\lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "C:\Users\86152\PycharmProjects\Huatuo-Llama-Med-Chinese-main\venv\lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "C:\Users\86152\PycharmProjects\Huatuo-Llama-Med-Chinese-main\venv\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "C:\Users\86152\PycharmProjects\Huatuo-Llama-Med-Chinese-main\venv\lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "C:\Users\86152\PycharmProjects\Huatuo-Llama-Med-Chinese-main\venv\lib\site-packages\bitsandbytes\cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
(venv) PS C:\Users\86152\PycharmProjects\Huatuo-Llama-Med-Chinese-main> 
出现这种bug，不知道是什么引起的，应该怎么解决

**Comment by s65b40** [comment]
CUDA环境变量存在问题，请确定已下载和GPU相符的cuda，并将其添加至环境变量

**Comment by cweihua** [comment]
> CUDA环境变量存在问题，请确定已下载和GPU相符的cuda，并将其添加至环境变量

我查了我的GPU能够运行的cuda最高版本是11.7，我装了11.6，cudnn和pytorch都是选和11.6一致的，不知道整个过程中有没有出错的地方，如果CUDA环境变量有问题，是否部署的所有语言模型都不能运行，我部署的chatGLM的4int的网页版能够顺利运行，这能否证明我的CUDA没有问题，如果不能证明的话我只能重新一步步安装了，但我不知道哪一步错了，有可能重蹈覆辙
