### ISSUE TITLE
使用finetune.py微调代码，最后保存peft训练好的lora模型报错

### ISSUE THREAD

**Issue by Forever-Young-l** [SCIR-HI/Huatuo-Llama-Med-Chinese#54]
{'loss': 0.5511, 'learning_rate': 6.013071895424836e-06, 'epoch': 9.82}                                                                    
{'loss': 0.5611, 'learning_rate': 4.967320261437908e-06, 'epoch': 9.85}                                                                    
{'loss': 0.5368, 'learning_rate': 3.92156862745098e-06, 'epoch': 9.88}                                                                     
{'loss': 0.54, 'learning_rate': 2.875816993464052e-06, 'epoch': 9.91}                                                                      
{'eval_loss': 0.873585045337677, 'eval_runtime': 24.2816, 'eval_samples_per_second': 20.592, 'eval_steps_per_second': 2.595, 'epoch': 9.91}
 99%|███████████████████████████████████████████████████████████████████████████████████████████████▏| 2528/2550 [6:51:49<03:19,  9.05s/it/root/.local/conda/envs/huatuo_pytorch/lib/python3.10/site-packages/bitsandbytes-0.39.0-py3.10.egg/bitsandbytes/autograd/_functions.py:318: UserWarning: MatMul8bitLt: inputs will be cast from torch.float32 to float16 during quantization
  warnings.warn(f"MatMul8bitLt: inputs will be cast from {A.dtype} to float16 during quantization")
{'loss': 0.547, 'learning_rate': 1.830065359477124e-06, 'epoch': 9.95}                                                                     
{'loss': 0.5574, 'learning_rate': 7.843137254901959e-07, 'epoch': 9.98}                                                                    
100%|████████████████████████████████████████████████████████████████████████████████████████████████| 2550/2550 [6:55:07<00:00,  8.78s/it]The intermediate checkpoints of PEFT may not be saved correctly, using `TrainerCallback` to save adapter_model.bin in corresponding folders, here are some examples https://github.com/huggingface/peft/issues/96
Traceback (most recent call last):
  File "/root/share/Huatuo-Llama-Med-Chinese-main/finetune.py", line 298, in <module>
    fire.Fire(train)
  File "/root/.local/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/.local/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/.local/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/root/share/Huatuo-Llama-Med-Chinese-main/finetune.py", line 288, in train
    trainer.train(resume_from_checkpoint=resume_from_checkpoint)
  File "/root/share/transformers-main/src/transformers/trainer.py", line 1664, in train
    return inner_training_loop(
  File "/root/share/transformers-main/src/transformers/trainer.py", line 2062, in _inner_training_loop
    self._load_best_model()
  File "/root/share/transformers-main/src/transformers/trainer.py", line 2259, in _load_best_model
    self._issue_warnings_after_load(load_result)
UnboundLocalError: local variable 'load_result' referenced before assignment
wandb: Waiting for W&B process to finish... (failed 1).
wandb: 
wandb: Run history:
wandb:               eval/loss █▅▄▄▃▃▃▂▂▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▁▁▁▂▁▂▂▂▂▃▂▃▂▃▁▂▄▄▄▃▃▃▂▆▃▂▂▃▂▂█▃▃▇▃▃█▃▃▃
wandb: eval/samples_per_second ███▇█▇▇▇▇▆▇▆▇▆█▇▅▅▅▆▆▅▇▃▆▇▇▆▇▇▁▆▆▂▆▆▁▆▆▆
wandb:   eval/steps_per_second ███▇█▇▇▇▇▆▇▆▇▆█▇▅▅▅▆▆▅▇▃▆▇▇▆▇▇▁▆▆▂▆▆▁▆▆▆
wandb:             train/epoch ▁▁▁▁▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▆▇▇▇▇▇███
wandb:       train/global_step ▁▁▁▁▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇███
wandb:     train/learning_rate ▂▄▅▇███▇▇▇▇▇▆▆▆▆▆▅▅▅▅▅▄▄▄▄▄▃▃▃▃▃▂▂▂▂▂▁▁▁
wandb:              train/loss █▆▅▅▄▄▄▄▃▃▃▃▃▃▃▃▃▃▂▂▂▂▂▂▂▂▂▂▂▁▂▁▁▁▁▁▁▁▁▁
wandb: 
wandb: Run summary:
wandb:               eval/loss 0.87359
wandb:            eval/runtime 24.2816
wandb: eval/samples_per_second 20.592
wandb:   eval/steps_per_second 2.595
wandb:             train/epoch 9.98
wandb:       train/global_step 2544
wandb:     train/learning_rate 0.0
wandb:              train/loss 0.5574
wandb: 
wandb: You can sync this run to the cloud by running:
wandb: wandb sync /root/share/Huatuo-Llama-Med-Chinese-main/wandb/offline-run-20230530_171932-54t8q7ta
wandb: Find logs at: ./wandb/offline-run-20230530_171932-54t8q7ta/logs

**Comment by s65b40** [comment]
您好，看报错可能和resume_from_checkpoint传入的参数相关
