### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 93: illegal multibyte sequence

### ISSUE THREAD

**Issue by cookie925** [SCIR-HI/Huatuo-Llama-Med-Chinese#90]
Traceback (most recent call last):
  File "E:\wbjdata\QA\Huatuo-Llama-Med-Chinese-main\Huatuo-Llama-Med-Chinese-main\1.py", line 124, in <module>
    fire.Fire(main)
  File "E:\anaconda3\envs\LLAMA10\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "E:\anaconda3\envs\LLAMA10\lib\site-packages\fire\core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "E:\anaconda3\envs\LLAMA10\lib\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "E:\wbjdata\QA\Huatuo-Llama-Med-Chinese-main\Huatuo-Llama-Med-Chinese-main\1.py", line 36, in main
    prompter = Prompter(prompt_template)
  File "E:\wbjdata\QA\Huatuo-Llama-Med-Chinese-main\Huatuo-Llama-Med-Chinese-main\utils\prompter.py", line 22, in __init__
    self.template = json.load(fp)
  File "E:\anaconda3\envs\LLAMA10\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 93: illegal multibyte sequence
请问大家为什么会出现这种情况啊，是哪个文件出错了呢

**Comment by s65b40** [comment]
你好，大概率是读template的时候的编码问题，请pull仓库最新的版本并尝试，刚刚添加了utf-8编码

**Comment by cookie925** [comment]
> 你好，大概率是读template的时候的编码问题，请pull仓库最新的版本并尝试，刚刚添加了utf-8编码

谢谢，我等下试试。
我前天把prompter.py 文件21行的代码with open(file_name) as fp:  改成了 with open(file_name，encoding=‘utf-8’) 它也跑起来了，不过就是回答的时候有些特殊符号。

**Comment by cookie925** [comment]
> 你好，大概率是读template的时候的编码问题，请pull仓库最新的版本并尝试，刚刚添加了utf-8编码

谢谢，我等下试试。
我前天把prompter.py 文件21行的代码with open(file_name) as fp: 改成了 with open(file_name，encoding=‘utf-8’) 它意外的跑起来了，不过就是回答的时候有些特殊符号。
